### ISSUE TITLE
Twogtp running from command line issue

### ISSUE THREAD

**Issue by iopq** [Remi-Coulom/gogui#11]
When I type `C:\"Program Files (x86)"\GoGui\gogui-twogtp` I get the error:

Command does not allow arguments that are not options

It works 100% fine when I cd into the folder first

**Comment by Remi-Coulom** [comment]
Thanks for reporting this problem. This problem might be related to launch4j, and I don't know how to fix it. Maybe someone else knows.

If you need a workaround, you may be able to create a .bat file that cd to the folder first.

**Comment by iopq** [comment]
If you throw up the error and proceed anyway, I think that's good enough for me.
