### ISSUE TITLE
illegal reflective access warning

### ISSUE THREAD

**Issue by medovina** [Remi-Coulom/gogui#23]
I'm running gogui with OpenJDK 11.0.7 on Ubuntu 20.04.

Each time I run gogui, I see

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.gogui.gogui.Main$2 (file:/home/adam/local/share/gogui/lib/gogui.jar) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of net.sf.gogui.gogui.Main$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

It would be nice to fix the warning.

**Comment by Remi-Coulom** [comment]
Thanks for reporting the warning. We can also see it, and had not bothered to fix it.

I searched the web to understand the error, and found this:
https://sourceforge.net/p/jedit/bugs/3971/

I don't understand very well what would be the best way to fix this, and have no time to work on this at the moment. I may take a longer look later.

**Comment by medovina** [comment]
Great, thanks for the fix!
