### ISSUE TITLE
Attach twogtp command as engine fails every time

### ISSUE THREAD

**Issue by zookar** [Remi-Coulom/gogui#42]
![temp](https://github.com/Remi-Coulom/gogui/assets/23634092/d883a791-4c69-4147-a4d8-52156169154c)

It seems that gogui sends the gtp command "name" to gogui-twogtp, but gogui-twogtp fails to respond.

**Comment by Remi-Coulom** [comment]
Thanks for your feedback. I just tested, and it seems that gogui-twogtp does support the "name" command:

```
$ ./gogui-twogtp -black "gnugo --mode=gtp" -white "gnugo --mode=gtp"
name
= gogui-twogtp

quit
=
```

It may be that your error may be caused by the white or black program hanging,
