### ISSUE TITLE
Question about analyze command

### ISSUE THREAD

**Issue by herazul** [Remi-Coulom/gogui#8]
Hi,

I am running test with two LZ net, and i would like to have the results with duplicates games counting for the winrates. By default, duplicates games are excluded. Is it possible ?

**Comment by Remi-Coulom** [comment]
I checked the code, and there is no option to prevent ignoring duplicates.

**Comment by herazul** [comment]
:'( Would you consider adding it ? Is it a complex feature to add ?

**Comment by Remi-Coulom** [comment]
It is probably not complex, but I feel no motivation at all to implement it myself. Maybe someone else will.
